### ISSUE TITLE
unzip2 progress

### ISSUE THREAD

**Issue by vikbez** [terrierscript/gulp-unzip#13]
Hi;

What's missing on the unzip2 branch ?
Would love to have this in master as unzip does not handle non-compressed files in zipfiles.

Thanks ! :+1:

**Comment by suisho** [comment]
I try use unzip2 but cannnot test passed :cry: 

This because of cannot parse empty file.
(This issue is related https://github.com/glebdmitriew/node-unzip-2/issues/2 )

**Comment by UlisesGascon** [comment]
Hi all! This issues is now moved to `New Release` #21. Let's see if we can merge it :-)
