### ISSUE TITLE
New maintainer wanted

### ISSUE THREAD

**Issue by terrierscript** [terrierscript/gulp-unzip#20]
It is glad that this plugin is used some peoples.
But sadly, I'm not use gulp currently and feel to hard that technical catch up ( like version 4.0 ).
If anyone who want maintain this plugin, I'm welcome!

**Comment by terrierscript** [comment]
@UlisesGascon Thank you! 
I append collaborator!

**Comment by UlisesGascon** [comment]
Awesome! Thanks a lot! 

Let me check what issues are open and what known issues we have... ;-)

I will start to work on the compatibility with Gulp 4.0 too

**Comment by UlisesGascon** [comment]
I will start to work now in #21 .. I will close now this issue ;-)
